services:
  - type: web
    name: fyyzcrm
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: TZ
        value: Asia/Shanghai
      - key: JAVA_OPTS
        value: -Xms256m -Xmx400m -XX:+UseG1GC -Dfile.encoding=UTF-8